#!/bin/sh
echo "updating time"
rdate -s time.mit.edu
sleep 2
echo "*                               *"
echo "* plugin installed successfully *"
echo "*                               *"
echo "* Enigma2 restart is required!  *"
echo "*                               *"

exit 0

